name: WINDOWS 2019 RDP

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest  # تحديث الإصدار [[5]]
    timeout-minutes: 60  # تقليل وقت الانتظار لتجنب التوقف المفاجئ
    steps:
      - name: Download Ngrok.
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/start.bat -OutFile start.bat
          
      - name: Extract ngrok
        run: Expand-Archive ngrok.zip
        
      - name: Connect Ngrok.
        run: |
          ./ngrok/ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  # تأكد من إضافة السر [[7]]
          
      - name: Windows10 RDP.
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          
      - name: Tunnel.
        run: Start-Process Powershell -ArgumentList '-Noexit -Command "./ngrok/ngrok.exe tcp 3389 --region=us"'
        
      - name: Verify Ngrok
        run: Start-Sleep -Seconds 10
        
      - name: Connect Rdp.
        run: cmd /c start.bat
